[build]
  publish = "_site"
  command = "jekyll build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "jekyll serve"
  port = 8888
  publish = "_site"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
